### ISSUE TITLE
開発環境の全体像を資料としてまとめたい

### ISSUE THREAD

**Issue by KaNakayama** [exastro-suite/exastro-platform#23]

**Comment by shiota-2021** [comment]
## 背景
- 現状は、タスクが下からの積み上げになっており、認識のあったゴールに到達できるか不安がある。

## 価値
- 認証基盤、ITA、各チームが共通した認識をもち、各々のやることや不足が明確化される。
- タスクが明確化される

## 開発Tが試したい、やりたいこと
- 全体を認識できる資料を作成
- 各チームと全体像の認識合わせ

## 受入基準
- 開発に携わる人たちが開発環境の構築イメージを認識できるようになっていること
- 全体像が資料としてできていること
- 開発環境関連のタスクリストが作成できるようになること

## やらないこと
- none
