### ISSUE TITLE
DevContainerを使った共通認証基盤の開発環境を構築したい

### ISSUE THREAD

**Issue by KaNakayama** [exastro-suite/exastro-platform#25]

**Comment by shiota-2021** [comment]
## 背景
- DevContainerの開発環境がないため、効率的な開発ができていない

## 価値
- 効率的な開発ができるようになる
- 開発環境における問題点なども使用する上で発見できる

## 開発Tが試したい、やりたいこと
- 共通認証基盤をdevconteinar化する
- manifestファイルを受け取り、docker-composeを作成する。
- 一旦、現材の状態で行う。

## 受入基準
- DevContainerを使用した共通認証基盤の開発ができていること
- 必要と考えられるVSCODE拡張が導入されていること
- コーディング規約の機能を入れて試してみる
　（課題点などあれば整理しておく）
- リポジトリはソースと同じものに格納する

## やらないこと
- none
