### ISSUE TITLE
ExastroPlatformの使用イメージを作成したい

### ISSUE THREAD

**Issue by KaNakayama** [exastro-suite/exastro-platform#26]

**Comment by shiota-2021** [comment]
## 背景
- 全体構成の説明をする際に、全員で統一された認識を合わせるのに苦労する部分がある。

## 価値
- ユースケースにより、実際の全体図の構成がより具体化する

## 開発Tが試したい、やりたいこと
- none

## 受入基準
次のユースケースの使用イメージが作成されていること
何もないところからITA,EPOCHを使うところ）
- オーガナイゼーション作成
- ユーザー作成
- ワークスペース作成
- ワークスペースとユーザー紐づけ

## やらないこと
- 詳細な画面イメージの作成
