### ISSUE TITLE
ExastroPlatformの全体像をより明確化したい

### ISSUE THREAD

**Issue by Eiji-Nakahashi** [exastro-suite/exastro-platform#45]

**Comment by KaNakayama** [comment]
## 背景
- 作成した全体像をもとにイメージをすり合わせたが、想定した内容とは違っていた箇所が多く、改めて全員の意識・イメージを明確化すべきと思われた

## 価値
- オーガナイゼーション、ワークスペース等の概念についてExastro全体で共通認識を持つことができ、Exastroとして一貫性のあるシステムを構築できるようになる

## 開発Tが試したい、やりたいこと
- オーガナイゼーション、ワークスペース等の概念の明確化
- ユーザー視点で考えられていること

## 受入基準
- 打ち合わせで指摘やイメージ齟齬があった点が修正されている全体像ができていること
- ワークスペースの綺麗な分け方、環境違いで、ITA,EPOCHをどう考えるかが、ユーザ側の視点で考えれていること
- EPOCHのユースケースができていること

## やらないこと
- none
