### ISSUE TITLE
認証基盤のサンプルを扱えるようにしたい

### ISSUE THREAD

**Issue by Eiji-Nakahashi** [exastro-suite/exastro-platform#46]

**Comment by KaNakayama** [comment]
## 背景
- 認証基盤のコードがgitに登録されておらず、認証基盤のAPI開発ができるようになっていない
- 開発ができる状態となっていないので、devcontainerの検証が不十分となっている

## 価値
- 認証基盤の開発を進められるようになる
- 開発サンプルとして、他チームに提供できる

## 開発Tが試したい、やりたいこと
- 秘匿情報をソースからなくす

## 受入基準
- ソースがGitに登録できていること
- Forkして、開発環境に取り込んで、デバックができるようになっていること
- 開発プロセス（Git Commit & Push、pullrequest(merge))ができるようになっていること

## やらないこと
- none
