### ISSUE TITLE
開発環境を使った利用方法の手順書を作成したい

### ISSUE THREAD

**Issue by Eiji-Nakahashi** [exastro-suite/exastro-platform#47]

**Comment by KaNakayama** [comment]
## 背景
- 開発環境を構築したが、利用方法の手順がなく、Gitの運用方法やDebug実行などを利用手段をどういった方法・順番でできるか明確になっていない

## 価値
- 開発環境の利用方法が明確になり、より早く、統一された手順で開発を始められるようになる

## 開発Tが試したい、やりたいこと
- none

## 受入基準
- 通常に開発者が行う以下の手順が作成されていること
・gitの操作手順
・デバック操作（起動・デバッカ・APIテスト)


## やらないこと
- none
