### ISSUE TITLE
システム管理者のオーガナイゼーション管理機能の一覧・登録・削除画面を作成したい

### ISSUE THREAD

**Issue by tomoki01** [exastro-suite/exastro-platform#780]
## 背景
システム管理者が利用するAPIは準備できたが、コマンドラインからすべて実施する必要があり、必須パラメータの入力や確認の手段が容易ではない

## 価値
システム管理者用画面でオーガナイゼーションの管理ができるようになる

## 受入基準
システム管理者が画面からオーガナイゼーションの作成が表示できる

## 開発Tが試したい、確認したい事項
2画面
1モーダル
- 一覧
- 登録
- 削除

**Comment by Eiji-Nakahashi** [comment]
対応済み
