### ISSUE TITLE
システム管理者のオーガナイゼーション管理機能の編集・詳細画面を作成したい

### ISSUE THREAD

**Issue by tomoki01** [exastro-suite/exastro-platform#781]
## 背景
システム管理者が利用するAPIは準備できたが、コマンドラインからすべて実施する必要があり、必須パラメータの入力や確認の手段が容易ではない

## 価値
システム管理者用画面でオーガナイゼーションの管理ができるようになる

## 受入基準
システム管理者が画面からオーガナイゼーションの編集・詳細が表示できる

## 開発Tが試したい、確認したい事項
2画面
1モーダル
- 編集
- 詳細
- オーガナイゼーションリソースプラン設定

**Comment by Eiji-Nakahashi** [comment]
対応済み
