### ISSUE TITLE
【要望】Exastroにログインする際にHTTPSを強制される

### ISSUE THREAD

**Issue by nec-takeo-ekiba** [exastro-suite/exastro-platform#808]
## 概要
ITAをインストールした直後、システム管理者のコンソール画面や各オーガナイゼーションのアクセスがHTTPSに強制されてしまう。
証明書をインストールする仕組みが現在はない状況なので、デフォルトでHTTPSを強制するのを無効にしてほしい。

## 詳細
各レルムの設定で、”Require SSL"の初期値が、"external requests"となっているので、
これを "none" がデフォルトになるようにしてほしい。

![image](https://github.com/exastro-suite/exastro-platform/assets/82383024/8755981a-f6fe-4ac7-a880-578f5233fee5)

**Comment by Eiji-Nakahashi** [comment]
対応済み
